version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      # Use proxy instead of direct API URL
      # - REACT_APP_API_URL=http://localhost:5001/api
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - hospital-network

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=hospital_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=dhilipwind@gmail.com
      - SMTP_PASS=btjgrcxnxkngiadt
      - SMTP_FROM_NAME=Ayphen Hospital Dhilip
      - SMTP_FROM_EMAIL=dhilipwind@gmail.com
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRES_IN=1h
      - JWT_REFRESH_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - postgres
    networks:
      - hospital-network

  # PostgreSQL Service
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=hospital_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hospital-network

  # pgAdmin (Web UI for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hospital.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - hospital-network

networks:
  hospital-network:
    driver: bridge

volumes:
  postgres_data:
