databases:
  - name: ayphen-hospital-db
    plan: free
    databaseName: hospital_db
    user: postgres

services:

  # Backend Service
  - type: web
    name: ayphen-hospital-backend
    env: docker
    plan: free
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ayphen-hospital-db
          property: connectionString
      - key: JWT_SECRET
        value: ayphen-hospital-super-secret-key-2025
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        value: dhilipwind@gmail.com
      - key: SMTP_PASS
        value: btjgrcxnxkngiadt
      - key: SMTP_FROM_NAME
        value: Ayphen Hospital
      - key: SMTP_FROM_EMAIL
        value: dhilipwind@gmail.com
      - key: FRONTEND_URL
        value: https://ayphen-hospital-frontend.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  # Frontend Service
  - type: web
    name: ayphen-hospital-frontend
    env: static
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://ayphen-hospital-backend.onrender.com
      - key: REACT_APP_GOOGLE_CLIENT_ID
        sync: false
